// AUTO-GENERATED by scripts/gen_suffering_cards.mjs — DO NOT EDIT
// Source: src/politikum/cards.yaml

import type { PolitikumCardType } from '../politikum';

export type PolitikumYamlCardDef = {
  id: string;
  type: PolitikumCardType;
  vp: number;
  count?: number;
  tags?: string[];
  text?: string;
  timing?: string;
  abilityKey?: string;
  params?: Record<string, any>;
};

export const POLITIKUM_YAML_CARDS: PolitikumYamlCardDef[] = [
  {
    "id": "persona_1",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Рунов",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ],
    "abilityKey": "on_enter_adjacent_bonus",
    "params": {
      "neighbors": [
        "persona_19",
        "persona_42"
      ],
      "tokens": 4
    }
  },
  {
    "id": "persona_2",
    "type": "persona",
    "vp": 7,
    "count": 1,
    "text": "Сережко",
    "tags": [
      "faction:leftwing",
      "gender:f"
    ]
  },
  {
    "id": "persona_3",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "SVTV",
    "tags": [
      "faction:rightwing"
    ],
    "abilityKey": "persona_3_on_enter_choice"
  },
  {
    "id": "persona_4",
    "type": "persona",
    "vp": 7,
    "count": 1,
    "text": "Яшин",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_4_on_enter_twitter_penalty"
  },
  {
    "id": "persona_5",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Певчих",
    "tags": [
      "faction:fbk",
      "gender:f"
    ],
    "abilityKey": "persona_5_discard_liberal_steal_tokens"
  },
  {
    "id": "persona_6",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Кашин",
    "tags": [
      "faction:rightwing",
      "gender:m"
    ],
    "abilityKey": "persona_6_on_action8_plus1"
  },
  {
    "id": "persona_7",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Каспаров",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_7_swap_two_in_coalition"
  },
  {
    "id": "persona_8",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Лазерсон",
    "tags": [
      "faction:leftwing",
      "gender:f"
    ]
  },
  {
    "id": "persona_9",
    "type": "persona",
    "vp": -3,
    "count": 1,
    "text": "Пономарёв",
    "tags": [
      "faction:liberal",
      "gender:m"
    ]
  },
  {
    "id": "persona_10",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Наки",
    "tags": [
      "faction:fbk",
      "gender:m"
    ]
  },
  {
    "id": "persona_11",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Соловей",
    "tags": [
      "faction:system",
      "gender:m"
    ]
  },
  {
    "id": "persona_12",
    "type": "persona",
    "abilityKey": "persona_12_on_enter_adjacent_red_buff",
    "vp": 3,
    "count": 1,
    "text": "Савин",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ]
  },
  {
    "id": "persona_13",
    "type": "persona",
    "abilityKey": "persona_13_retaliate_on_targeted_action",
    "vp": 2,
    "count": 1,
    "text": "Венедитков",
    "tags": [
      "faction:system",
      "gender:m"
    ]
  },
  {
    "id": "persona_14",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Ройзман",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "discard_one_persona_from_any_coalition"
  },
  {
    "id": "persona_15",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Пожарский",
    "tags": [
      "faction:rightwing",
      "gender:m"
    ]
  },
  {
    "id": "persona_16",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Кац",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_16_on_enter_draw3_discard3"
  },
  {
    "id": "persona_17",
    "type": "persona",
    "abilityKey": "persona_17_on_enter_steal_persona",
    "vp": 2,
    "count": 1,
    "text": "Арно",
    "tags": [
      "faction:liberal",
      "gender:f"
    ]
  },
  {
    "id": "persona_18",
    "type": "persona",
    "vp": 5,
    "count": 1,
    "text": "Соболь",
    "tags": [
      "faction:fbk",
      "gender:f"
    ]
  },
  {
    "id": "persona_19",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Гиркин",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ],
    "abilityKey": "on_enter_adjacent_bonus",
    "params": {
      "neighbors": [
        "persona_1",
        "persona_42"
      ],
      "tokens": 4
    }
  },
  {
    "id": "persona_20",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Быков",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_20_on_enter_take_from_discard"
  },
  {
    "id": "persona_21",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Штефанов",
    "tags": [
      "faction:leftwing",
      "gender:m"
    ],
    "abilityKey": "persona_21_on_enter_invert_tokens"
  },
  {
    "id": "persona_22",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Светов",
    "tags": [
      "faction:rightwing",
      "gender:m"
    ],
    "abilityKey": "persona_22_global_enter_mods"
  },
  {
    "id": "persona_23",
    "type": "persona",
    "vp": 4,
    "count": 1,
    "text": "Волков",
    "tags": [
      "faction:fbk",
      "gender:m"
    ],
    "abilityKey": "persona_23_on_enter_self_inflict_draw"
  },
  {
    "id": "persona_24",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Латынина",
    "tags": [
      "faction:rightwing",
      "gender:f"
    ],
    "abilityKey": "persona_24_passive_dual_leftwing_scaler"
  },
  {
    "id": "persona_25",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Надеждин",
    "tags": [
      "faction:system",
      "gender:m"
    ]
  },
  {
    "id": "persona_26",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Демушкин",
    "tags": [
      "faction:rightwing",
      "gender:m"
    ],
    "abilityKey": "persona_26_on_enter_purge_red_inherit_plus"
  },
  {
    "id": "persona_27",
    "type": "persona",
    "vp": 7,
    "count": 1,
    "text": "Юдин",
    "tags": [
      "faction:leftwing",
      "gender:m"
    ]
  },
  {
    "id": "persona_28",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Ведута",
    "tags": [
      "faction:fbk",
      "gender:f"
    ],
    "abilityKey": "persona_28_on_enter_steal_plus_tokens"
  },
  {
    "id": "persona_29",
    "type": "persona",
    "vp": 4,
    "count": 1,
    "text": "Юнеман",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ]
  },
  {
    "id": "persona_30",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Ходорковский",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_30_on_enter_buff_liberals"
  },
  {
    "id": "persona_31",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Шлосберг",
    "tags": [
      "faction:system",
      "gender:m",
      "persona:immovable"
    ]
  },
  {
    "id": "persona_32",
    "type": "persona",
    "vp": 3,
    "count": 1,
    "text": "Плющев",
    "tags": [
      "faction:liberal",
      "gender:m"
    ],
    "abilityKey": "persona_32_activate_bounce"
  },
  {
    "id": "persona_33",
    "type": "persona",
    "vp": 0,
    "count": 1,
    "text": "Собчак",
    "tags": [
      "faction:neutral",
      "gender:f"
    ],
    "abilityKey": "persona_33_on_enter_choose_faction"
  },
  {
    "id": "persona_34",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Милов",
    "tags": [
      "faction:fbk",
      "gender:m"
    ],
    "abilityKey": "persona_34_on_enter_guess_topdeck"
  },
  {
    "id": "persona_35",
    "type": "persona",
    "vp": 4,
    "count": 1,
    "text": "Жданов",
    "tags": [
      "faction:fbk",
      "gender:m"
    ],
    "abilityKey": "persona_35_no_ability"
  },
  {
    "id": "persona_36",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Кагалицкий",
    "tags": [
      "faction:leftwing",
      "gender:m"
    ],
    "abilityKey": "persona_36_passive_ignore_action7"
  },
  {
    "id": "persona_37",
    "type": "persona",
    "vp": 4,
    "count": 1,
    "text": "Гуриев",
    "tags": [
      "faction:leftwing",
      "gender:m"
    ],
    "abilityKey": "persona_37_on_enter_bribe_and_silence"
  },
  {
    "id": "persona_38",
    "type": "persona",
    "vp": 0,
    "count": 1,
    "text": "VotVot",
    "tags": [
      "faction:leftwing"
    ],
    "abilityKey": "persona_38_global_event_token_vacuum"
  },
  {
    "id": "persona_39",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Лефт",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ]
  },
  {
    "id": "persona_40",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Дунцова",
    "tags": [
      "faction:system",
      "gender:f"
    ],
    "abilityKey": "place_tokens_plus_vp",
    "params": {
      "tokens": 3,
      "delta": 1
    }
  },
  {
    "id": "persona_41",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Дождь",
    "tags": [
      "faction:liberal"
    ],
    "abilityKey": "persona_41_on_enter_buff_fbk"
  },
  {
    "id": "persona_42",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Стрелков",
    "tags": [
      "faction:red_nationalist",
      "gender:m"
    ],
    "abilityKey": "on_enter_adjacent_bonus",
    "params": {
      "neighbors": [
        "persona_1",
        "persona_19"
      ],
      "tokens": 4
    }
  },
  {
    "id": "persona_43",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Доха",
    "tags": [
      "faction:leftwing"
    ],
    "abilityKey": "persona_43_on_enter_drain_rightwing"
  },
  {
    "id": "persona_44",
    "type": "persona",
    "vp": 1,
    "count": 1,
    "text": "Рудой",
    "tags": [
      "faction:leftwing",
      "gender:m"
    ]
  },
  {
    "id": "persona_45",
    "type": "persona",
    "vp": 2,
    "count": 1,
    "text": "Шульман",
    "tags": [
      "faction:liberal",
      "gender:f"
    ],
    "abilityKey": "persona_45_steal_from_opponent"
  },
  {
    "id": "event_1",
    "type": "event",
    "vp": 0,
    "count": 3,
    "timing": "on_draw",
    "abilityKey": "place_tokens_plus_vp",
    "params": {
      "tokens": 3,
      "delta": 1
    }
  },
  {
    "id": "event_2",
    "type": "event",
    "vp": 0,
    "count": 2,
    "timing": "on_draw",
    "abilityKey": "place_tokens_plus_vp",
    "params": {
      "tokens": 2,
      "delta": 1
    }
  },
  {
    "id": "event_3",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "place_tokens_plus_vp",
    "params": {
      "tokens": 5,
      "delta": 1
    }
  },
  {
    "id": "event_10",
    "type": "event",
    "vp": 0,
    "count": 2,
    "timing": "on_draw",
    "abilityKey": "place_tokens_plus_vp",
    "params": {
      "tokens": 4,
      "delta": 1
    }
  },
  {
    "id": "event_11",
    "type": "event",
    "vp": 0,
    "count": 2,
    "timing": "on_draw",
    "abilityKey": "event_draw_cards",
    "params": {
      "count": 2
    }
  },
  {
    "id": "event_12a",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "event_faction_minus1_draw1",
    "params": {
      "factionTag": "faction:fbk"
    },
    "tags": [
      "event_type:twitter_squabble"
    ]
  },
  {
    "id": "event_12b",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "event_12b_discard_others_hand",
    "tags": [
      "event_type:twitter_squabble"
    ]
  },
  {
    "id": "event_12c",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "event_faction_minus1_draw1",
    "params": {
      "factionTag": "faction:liberal"
    },
    "tags": [
      "event_type:twitter_squabble"
    ]
  },
  {
    "id": "event_15",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "event_shuffle_all_hands_redeal"
  },
  {
    "id": "event_16",
    "type": "event",
    "vp": 0,
    "count": 1,
    "timing": "on_draw",
    "abilityKey": "event_16_discard_self_persona_then_draw1"
  },
  {
    "id": "action_4",
    "type": "action",
    "vp": 0,
    "count": 2,
    "timing": "on_play"
  },
  {
    "id": "action_5",
    "type": "action",
    "vp": 0,
    "count": 1,
    "timing": "on_play"
  },
  {
    "id": "action_6",
    "type": "action",
    "vp": 0,
    "count": 1,
    "timing": "response"
  },
  {
    "id": "action_7",
    "type": "action",
    "vp": 0,
    "count": 3,
    "timing": "on_play",
    "tags": [
      "action:block_persona",
      "action:persists"
    ]
  },
  {
    "id": "action_8",
    "type": "action",
    "vp": 0,
    "count": 8,
    "timing": "response"
  },
  {
    "id": "action_9",
    "type": "action",
    "vp": 0,
    "count": 2,
    "timing": "on_play"
  },
  {
    "id": "action_13",
    "type": "action",
    "vp": 0,
    "count": 2,
    "timing": "on_play",
    "tags": [
      "action:shield",
      "action:persists"
    ]
  },
  {
    "id": "action_14",
    "type": "action",
    "vp": 0,
    "count": 1,
    "timing": "response",
    "tags": [
      "action:cancel_effect_on_persona"
    ]
  },
  {
    "id": "action_17",
    "type": "action",
    "vp": 0,
    "count": 1,
    "timing": "on_play",
    "tags": [
      "action:minus_tokens"
    ]
  },
  {
    "id": "action_18",
    "type": "action",
    "vp": 0,
    "count": 2,
    "timing": "on_play",
    "tags": [
      "action:retrieve_persona_discard"
    ]
  }
] as any;
